## NumPy Basics: Arrays and Vectorized Computation



### Introduction



NumPy, short for Numerical Python, is one of the most important
foundational packages for numerical computing in Python. 



In [2]:
import numpy as np
np.random.seed(2255)
import matplotlib.pyplot as plt

Here are some of the things in NumPy:

-   ndarray, an efficient multidimensional array providing fast
    array-oriented arithmetic operations and flexible *broadcasting*
    capabilities;
-   Mathematical functions for fast operations on entire arrays of data
    without having to write loops;
-   Tools for reading/writing array data to disk and working with
    memory-mapped files;
-   Linear algebra, random number generation, and Fourier transform
    capabilities;
-   A C API for connecting NumPy with libraries written in C, C++, or
    FORTRAN.

To see the performance difference, consider a NumPy array of one million integers, and the equivalent Python list



In [3]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

Now let's multiply each sequence by 2:



In [4]:
import time

start = time.time()
my_arr2 = my_arr * 2 
print(time.time() - start)

start = time.time()
my_list2 = [x * 2 for x in my_list]
print(time.time() - start)

0.008174657821655273
0.03271913528442383


NumPy-based algorithms are generally 10 to 100 times faster (or more)
than their pure Python counterparts and use significantly less memory.



### The NumPy ndarray: A Multidimensional Array



One of the key features of NumPy is its N-dimensional array object, or
ndarray, which is a fast, flexible container for large datasets in
Python. Arrays enable you to perform mathematical operations on whole
blocks of data using similar syntax to the equivalent operations between
scalar elements.



In [5]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

Mathematical operations with `data`:



In [8]:
L = [[1.5, -0.1, 3], [0, -3, 6.5]]
L

[[1.5, -0.1, 3], [0, -3, 6.5]]

In [10]:
L * 2

[[1.5, -0.1, 3], [0, -3, 6.5], [1.5, -0.1, 3], [0, -3, 6.5]]

In [11]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [13]:
L + L

[[1.5, -0.1, 3], [0, -3, 6.5], [1.5, -0.1, 3], [0, -3, 6.5]]

-   An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type.
-   Every array has a `shape`, a tuple indicating the size of each dimension, and a `dtype`, an object describing the *data type* of the array:



In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

#### Creating



The easiest way to create an array is to use the `array` function. This
accepts any sequence-like object (including other arrays) and produces a
new NumPy array containing the passed data. For example, a list is a
good candidate for conversion:



In [16]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted
into a multidimensional array:



In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since `data2` was a list of lists, the NumPy array `arr2` has two
dimensions, with shape inferred from the data. We can confirm this by
inspecting the `ndim` and `shape` attributes:



In [19]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

Unless explicitly specified, `numpy.array` tries to infer a good data type for the array
that it creates. The data type is stored in a special `dtype` metadata
object; for example, in the previous two examples we have:



In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In addition to `numpy.array`, there are a number of other functions for
creating new arrays. As examples, `numpy.zeros` and `numpy.ones` create
arrays of 0s or 1s, respectively, with a given length or shape.
`numpy.empty` creates an array without initializing its values to any
particular value. To create a higher dimensional array with these
methods, pass a tuple for the shape:



In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.empty((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.empty((2, 3, 70))

array([[[2.65539743e-314, 2.65539744e-314, 2.65539744e-314,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         2.65539743e-314, 2.65539744e-314, 5.43472210e-323,
         0.00000000e+000, 3.95252517e-323, 2.12199579e-314,
                     nan, 2.20866881e-314, 4.44659081e-323,
         1.06099790e-313, 1.18575755e-322, 2.16545126e-314,
         4.94065646e-324, 2.24578852e-314, 4.44659081e-323,
         1.06099790e-313, 2.12199580e-314, 2.16545126e-314,
         9.88131292e-324, 2.24587915e-314, 4.44659081e-323,
         1.06099790e-313,             nan, 2.25886228e-314,
         2.12199582e-314, 2.25886138e-314, 5.78056806e-321,
         2.25886228e-314, 2.42092166e-322, 2.25886230e-314,
                     nan, 2.16545126e-314, 2.12199579e-314,
         2.33419537e-313, 4.44659081e-323, 1.06099790e-313,
         2.12199580e-314, 2.16545126e-314,             nan,
         2.20866881e-314, 4.44659081e-323, 1.06099790e-313,
         5.54341655e-321, 2.25886254e-31

It's not safe to assume that `numpy.empty` will return an array of all
zeros. This function returns uninitialized memory and thus may contain
nonzero "garbage" values. You should use this function only if you
intend to populate the new array with data.

`numpy.arange` is an array-valued version of the built-in Python `range`
function:



In [ ]:
np.arange(15)

Here is a short list of standard array creation functions. Since NumPy is
focused on numerical computing, the data type, if not specified, will in
many cases be `float64` (floating point).


| Function|Description|
|---|---|
| <code>array</code>|Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default|
| <code>asarray</code>|Convert input to ndarray, but do not copy if the input is already an ndarray|
| <code>arange</code>|Like the built-in <code>range</code> but returns an ndarray instead of a list|
| <code>ones, ones_like</code>|Produce an array of all 1s with the given shape and data type; <code>ones_like</code> takes another array and produces a <code>ones</code> array of the same shape and data type|
| <code>zeros, zeros_like</code>|Like <code>ones</code> and <code>ones_like</code> but producing arrays of 0s instead|
| <code>empty, empty_like</code>|Create new arrays by allocating new memory, but do not populate with any values like <code>ones</code> and <code>zeros</code>|
| <code>full, full_like</code>|Produce an array of the given shape and data type with all values set to the indicated "fill value"; <code>full_like</code> takes another array and produces a filled array of the same shape and data type|
| <code>eye, identity</code>|Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)|



#### Data Types

The *data type* or `dtype` is a special object containing the
information (or *metadata*, data about data) the ndarray needs to
interpret a chunk of memory as a particular type of data:



In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype, arr2.dtype

Data types are a source of NumPy's flexibility for interacting with data
coming from other systems. In most cases they provide a mapping directly
onto an underlying disk or memory representation, which makes it
possible to read and write binary streams of data to disk and to connect
to code written in a low-level language like C or FORTRAN. The numerical
data types are named the same way: a type name, like `float` or `int`,
followed by a number indicating the number of bits per element. A
standard double-precision floating-point value (what's used under the
hood in Python's `float` object) takes up 8 bytes or 64 bits. Thus, this
type is known in NumPy as `float64`.

Here is a full listing of NumPy's supported data types.


| Type|Type code|Description|
|---|---|---|
| <code>int8, uint8</code>|<code>i1, u1</code>|Signed and unsigned 8-bit (1 byte) integer types|
| <code>int16, uint16</code>|<code>i2, u2</code>|Signed and unsigned 16-bit integer types|
| <code>int32, uint32</code>|<code>i4, u4</code>|Signed and unsigned 32-bit integer types|
| <code>int64, uint64</code>|<code>i8, u8</code>|Signed and unsigned 64-bit integer types|
| <code>float16</code>|<code>f2</code>|Half-precision floating point|
| <code>float32</code>|<code>f4 or f</code>|Standard single-precision floating point; compatible with C float|
| <code>float64</code>|<code>f8 or d</code>|Standard double-precision floating point; compatible with C double and Python <code>float</code> object|
| <code>float128</code>|<code>f16 or g</code>|Extended-precision floating point|
| <code>complex64</code>, <code>complex128</code>, <code>complex256</code>|<code>c8, c16, c32</code>|Complex numbers represented by two 32, 64, or 128 floats, respectively|
| <code>bool</code>|?|Boolean type storing <code>True</code> and <code>False</code> values|
| <code>object</code>|O|Python object type; a value can be any Python object|
| <code>string_</code>|S|Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use <code>'S10'</code>|
| <code>unicode_</code>|U|Fixed-length Unicode type (number of bytes platform specific); same specification semantics as <code>string_</code> (e.g., <code>'U10'</code>)|

You can explicitly convert or *cast* an array from one data type to
another using ndarray's `astype` method:



In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

In [ ]:
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

In [ ]:
arr.astype(np.int32)

If you have an array of strings representing numbers, you can use
`astype` to convert them to numeric form:



In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings

In [ ]:
numeric_strings.astype(float)

Be cautious when using the `numpy.string_` type, as string data in NumPy
is fixed size and may truncate input without warning. pandas has more
intuitive out-of-the-box behavior on non-numeric data.

You can also use another array's `dtype` attribute:



In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

#### Arithmetic with NumPy



Arrays are important because they enable you to express batch operations
on data without writing any `for` loops. NumPy users call this
*vectorization*. Any arithmetic operations between equal-size arrays
apply the operation element-wise:



In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

In [ ]:
arr * arr

In [ ]:
arr - arr

Arithmetic operations with scalars propagate the scalar argument to each
element in the array:



In [ ]:
1 / arr

In [ ]:
arr ** 2

Comparisons between arrays of the same size yield Boolean arrays:



In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

In [ ]:
arr2 > arr

#### Basic Indexing and slicing

NumPy array indexing is a deep topic, as there are many ways you may
want to select a subset of your data or individual elements.
One-dimensional arrays are simple; on the surface they act similarly to
Python lists:



In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8]

In [ ]:
arr[5:8] = 12
arr

As you can see, if you assign a scalar value to a slice, as in
`arr[5:8] = 12`, the value is propagated (or *broadcast* henceforth) to
the entire selection.

An important first distinction from Python's built-in lists is that
array slices are views on the original array. This means that the data
is not copied, and any modifications to the view will be reflected in
the source array.

To give an example of this, I first create a slice of `arr`:



In [ ]:
arr_slice = arr[5:8]
arr_slice

Now, when I change values in `arr_slice`, the mutations are reflected in
the original array `arr`:



In [ ]:
arr_slice[1] = 12345
arr

The "bare" slice `[:]` will assign to all values in an array:



In [ ]:
arr_slice[:] = 64
arr

If you are new to NumPy, you might be surprised by this, especially if
you have used other array programming languages that copy data more
eagerly. As NumPy has been designed to be able to work with very large
arrays, you could imagine performance and memory problems if NumPy
insisted on always copying data.

If you want a copy of a slice of an ndarray instead of a view, you will
need to explicitly copy the array&#x2014;for example, `arr[5:8].copy()`. As
you will see, pandas works this way, too.

With higher dimensional arrays, you have many more options. In a
two-dimensional array, the elements at each index are no longer scalars
but rather one-dimensional arrays:



In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

In [ ]:
arr2d[2]

Thus, individual elements can be accessed recursively. But that is a bit
too much work, so you can pass a comma-separated list of indices to
select individual elements. So these are equivalent:



In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0, 2]

![img](./figures/pda3_0401.png)

In multidimensional arrays, if you omit later indices, the returned
object will be a lower dimensional ndarray consisting of all the data
along the higher dimensions. So in the 2 × 2 × 3 array `arr3d`:



In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

`arr3d[0]` is a 2 × 3 array:



In [ ]:
arr3d[0]

Both scalar values and arrays can be assigned to `arr3d[0]`:



In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

In [ ]:
arr3d[0] = old_values
arr3d

Similarly, `arr3d[1, 0]` gives you all of the values whose indices start
with `(1, 0)`, forming a one-dimensional array:



In [ ]:
arr3d[1, 0]

This expression is the same as though we had indexed in two steps:



In [ ]:
x = arr3d[1]
x
x[0]

Note that in all of these cases where subsections of the array have been
selected, the returned arrays are views.

This multidimensional indexing syntax for NumPy arrays will not work
with regular Python objects, such as lists of lists.



##### Indexing with slices

Like one-dimensional objects such as Python lists, ndarrays can be
sliced with the familiar syntax:



In [ ]:
arr
arr[1:6]

Consider the two-dimensional array from before, `arr2d`. Slicing this
array is a bit different:



In [ ]:
arr2d

In [ ]:
arr2d[:2]

As you can see, it has sliced along axis 0, the first axis. A slice,
therefore, selects a range of elements along an axis. It can be helpful
to read the expression `arr2d[:2]` as "select the first two rows of
`arr2d`."

You can pass multiple slices just like you can pass multiple indexes:



In [ ]:
arr2d[:2, 1:]

When slicing like this, you always obtain array views of the same number
of dimensions. By mixing integer indexes and slices, you get lower
dimensional slices.

For example, I can select the second row but only the first two columns,
like so:



In [ ]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

Here, while `arr2d` is two-dimensional, `lower_dim_slice` is
one-dimensional, and its shape is a tuple with one axis size:



In [ ]:
lower_dim_slice.shape

Similarly, I can select the third column but only the first two rows,
like so:



In [ ]:
arr2d[:2, 2]

Note that a colon by itself means to take the
entire axis, so you can slice only higher dimensional axes by doing:



In [ ]:
arr2d[:, :1]

Of course, assigning to a slice expression assigns to the whole
selection:



In [ ]:
arr2d[:2, 1:] = 0
arr2d

![img](./figures/pda3_0402.png)



#### Boolean



Let's consider an example where we have some data in an array and an
array of names with duplicates:



In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

In [ ]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
data

Suppose each name corresponds to a row in the `data` array and we wanted
to select all the rows with the corresponding name `"Bob"`. Like
arithmetic operations, comparisons (such as `==`) with arrays are also
vectorized. Thus, comparing `names` with the string `"Bob"` yields a
Boolean array:



In [ ]:
names == "Bob"

This Boolean array can be passed when indexing the array:



In [ ]:
data[names == "Bob"]

The Boolean array must be of the same length as the array axis it's
indexing. You can even mix and match Boolean arrays with slices or
integers (or sequences of integers; more on this later).

In these examples, I select from the rows where `names =` "Bob"= and
index the columns, too:



In [ ]:
data[names == "Bob", 1:]

In [ ]:
data[names == "Bob", 1]

To select everything but `"Bob"` you can either use `!=` or negate the
condition using `~`:



In [ ]:
names != "Bob"

In [ ]:
~(names == "Bob")

In [ ]:
data[names != "Bob"]

The `~` operator can be useful when you want to invert a Boolean array
referenced by a variable:



In [ ]:
cond = names == "Bob"
data[~cond]

To select two of the three names to combine multiple Boolean conditions,
use Boolean arithmetic operators like `&` (and) and `|` (or):



In [ ]:
mask = (names == "Bob") | (names == "Will")
mask

In [ ]:
data[mask]

Selecting data from an array by Boolean indexing and assigning the
result to a new variable *always* creates a copy of the data, even if
the returned array is unchanged.

The Python keywords `and` and `or` do not work with Boolean arrays. Use
`&` (and) and `|` (or) instead.

Setting values with Boolean arrays works by substituting the value or
values on the righthand side into the locations where the Boolean
array's values are `True`. To set all of the negative values in `data`
to 0, we need only do:



In [ ]:
data[data < 0] = 0
data

You can also set whole rows or columns using a one-dimensional Boolean
array:



In [ ]:
data[names != "Joe"] = 7
data

As we will see later, these types of operations on two-dimensional data
are convenient to do with pandas.



#### Fancy indexing

*Fancy indexing* is a term adopted by NumPy to describe indexing using
integer arrays. Suppose we had an 8 × 4 array:



In [ ]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

To select a subset of the rows in a particular order, you can simply
pass a list or ndarray of integers specifying the desired order:



In [ ]:
arr[[4, 3, 0, 6]]

Hopefully this code did what you expected! Using negative indices
selects rows from the end:



In [ ]:
arr[[-3, -5, -7]]

Passing multiple index arrays does something slightly different; it
selects a one-dimensional array of elements corresponding to each tuple
of indices:



In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

Here the elements `(1, 0), (5, 3), (7, 1)`, and `(2, 2)` were selected.
The result of fancy indexing with as many integer arrays as there are
axes is always one-dimensional.

The behavior of fancy indexing in this case is a bit different from what
some users might have expected (myself included), which is the
rectangular region formed by selecting a subset of the matrix's rows and
columns. Here is one way to get that:



In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

Keep in mind that fancy indexing, unlike slicing, always copies the data
into a new array when assigning the result to a new variable. If you
assign values with fancy indexing, the indexed values will be modified:



In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

#### Transposing Arrays and Swapping



Transposing is a special form of reshaping that similarly returns a view
on the underlying data without copying anything. Arrays have the
`transpose` method and the special `T` attribute:



In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

In [ ]:
arr.T

When doing matrix computations, you may do this very often&#x2014;for
example, when computing the inner matrix product using `numpy.dot`:



In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

In [ ]:
np.dot(arr.T, arr)

The `@` infix operator is another way to do matrix multiplication:



In [ ]:
arr.T @ arr

Simple transposing with `.T` is a special case of swapping axes. ndarray
has the method `swapaxes`, which takes a pair of axis numbers and
switches the indicated axes to rearrange the data:



In [ ]:
arr.swapaxes(0, 1)

`swapaxes` similarly returns a view on the data without making a copy.



### Pseudorandom Number



The `numpy.random` module supplements the built-in Python `random`
module with functions for efficiently generating whole arrays of sample
values from many kinds of probability distributions. For example, you
can get a 4 × 4 array of samples from the standard normal distribution
using `numpy.random.standard_normal`:



In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples

Python's built-in `random` module, by contrast, samples only one value
at a time. As you can see from this benchmark, `numpy.random` is well
over an order of magnitude faster for generating very large samples:



In [ ]:
from random import normalvariate
N = 1_000_000

start = time.time()
samples = [normalvariate(0, 1) for _ in range(N)]
print(time.time() - start)

start = time.time()
np.random.standard_normal(N)
print(time.time() - start)

These random numbers are not truly random (rather, *pseudorandom*) but
instead are generated by a configurable random number generator that
determines deterministically what values are created. Functions like
`numpy.random.standard_normal` use the `numpy.random` module's default
random number generator, but your code can be configured to use an
explicit generator:



In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
data

The `seed` argument is what determines the initial state of the
generator, and the state changes each time the `rng` object is used to
generate data. The generator object `rng` is also isolated from other
code which might use the `numpy.random` module:



In [ ]:
type(rng)

Here is a partial list of methods available on random generator objects like
`rng`.


| Method|Description|
|---|---|
| <code>permutation</code>|Return a random permutation of a sequence, or return a permuted range|
| <code>shuffle</code>|Randomly permute a sequence in place|
| <code>uniform</code>|Draw samples from a uniform distribution|
| <code>integers</code>|Draw random integers from a given low-to-high range|
| <code>standard_normal</code>|Draw samples from a normal distribution with mean 0 and standard deviation 1|
| <code>binomial</code>|Draw samples from a binomial distribution|
| <code>normal</code>|Draw samples from a normal (Gaussian) distribution|
| <code>beta</code>|Draw samples from a beta distribution|
| <code>chisquare</code>|Draw samples from a chi-square distribution|
| <code>gamma</code>|Draw samples from a gamma distribution|
| <code>uniform</code>|Draw samples from a uniform [0, 1) distribution|



### Universal Functions: Fast Element-Wise Array



A universal function, or *ufunc*, is a function that performs
element-wise operations on data in ndarrays. You can think of them as
fast vectorized wrappers for simple functions that take one or more
scalar values and produce one or more scalar results.

Many ufuncs are simple element-wise transformations, like `numpy.sqrt`
or `numpy.exp`:



In [ ]:
arr = np.arange(10)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

These are referred to as *unary* ufuncs. Others, such as `numpy.add` or
`numpy.maximum`, take two arrays (thus, *binary* ufuncs) and return a
single array as the result:



In [ ]:
x = rng.standard_normal(8)
x

In [ ]:
y = rng.standard_normal(8)
y

In [ ]:
np.maximum(x, y)

In this example, `numpy.maximum` computed the element-wise maximum of
the elements in `x` and `y`.

While not common, a ufunc can return multiple arrays. `numpy.modf` is
one example: a vectorized version of the built-in Python `math.modf`, it
returns the fractional and integral parts of a floating-point array:



In [ ]:
arr = rng.standard_normal(7) * 5
arr

In [ ]:
remainder, whole_part = np.modf(arr)
remainder

In [ ]:
whole_part

Ufuncs accept an optional `out` argument that allows them to assign
their results into an existing array rather than create a new one:



In [ ]:
arr

In [ ]:
np.add(arr, 1)

In [ ]:
out = np.zeros_like(arr)
out

In [ ]:
np.add(arr, 1, out=out)
out

Here are two lists of some of NumPy' ufuncs. New ufuncs continue to be added
to NumPy, so consulting the online NumPy documentation is the best way
to get a comprehensive listing and stay up to date.


| Function|Description|
|---|---|
| <code>abs, fabs</code>|Compute the absolute value element-wise for integer, floating-point, or complex values|
| <code>sqrt</code>|Compute the square root of each element (equivalent to <code>arr ** 0.5</code>)|
| <code>square</code>|Compute the square of each element (equivalent to <code>arr ** 2</code>)|
| <code>exp</code>|Compute the exponent e<sup>x</sup> of each element|
| <code>log, log10, log2, log1p</code>|Natural logarithm (base <i>e</i>), log base 10, log base 2, and log(1 + x), respectively|
| <code>sign</code>|Compute the sign of each element: 1 (positive), 0 (zero), or &#x2013;1 (negative)|
| <code>ceil</code>|Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)|
| <code>floor</code>|Compute the floor of each element (i.e., the largest integer less than or equal to each element)|
| <code>rint</code>|Round elements to the nearest integer, preserving the <code>dtype</code>|
| <code>modf</code>|Return fractional and integral parts of array as separate arrays|
| <code>isnan</code>|Return Boolean array indicating whether each value is <code>NaN</code> (Not a Number)|
| <code>isfinite, isinf</code>|Return Boolean array indicating whether each element is finite (non-<code>inf</code>, non-<code>NaN</code>) or infinite, respectively|
| <code>cos, cosh, sin, sinh, tan, tanh</code>|Regular and hyperbolic trigonometric functions|
| <code>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</code>|Inverse trigonometric functions|
| <code>logical_not</code>|Compute truth value of <code>not</code> <code>x</code> element-wise (equivalent to <code>~arr</code>)|


| Function|Description|
|---|---|
| <code>add</code>|Add corresponding elements in arrays|
| <code>subtract</code>|Subtract elements in second array from first array|
| <code>multiply</code>|Multiply array elements|
| <code>divide, floor_divide</code>|Divide or floor divide (truncating the remainder)|
| <code>power</code>|Raise elements in first array to powers indicated in second array|
| <code>maximum, fmax</code>|Element-wise maximum; <code>fmax</code> ignores <code>NaN</code>|
| <code>minimum, fmin</code>|Element-wise minimum; <code>fmin</code> ignores <code>NaN</code>|
| <code>mod</code>|Element-wise modulus (remainder of division)|
| <code>copysign</code>|Copy sign of values in second argument to values in first argument|
| <code>greater, greater_equal, less, less_equal, equal, not_equal</code>|Perform element-wise comparison, yielding Boolean array (equivalent to infix operators <code>&gt;, &gt;</code>, &lt;, &lt;=, <code>=, !=</code>)|
| <code>logical_and</code>|Compute element-wise truth value of AND (<code>&amp;</code>) logical operation|
| <code>logical_or</code>|Compute element-wise truth value of OR (=|=) logical operation|
| <code>logical_xor</code>|Compute element-wise truth value of XOR (<code>^</code>) logical operation|



### Array-Oriented Programming with Arrays

-   Using NumPy arrays enables you to express many kinds of data processing
    tasks as concise array expressions that might otherwise require writing
    loops. 
    -   This practice of replacing explicit loops with array expressions is referred to by some people as *vectorization*.
    -   In general, vectorized array operations will usually be significantly faster than their pure Python equivalents, with the biggest impact in any kind of numerical computations.

As a simple example, suppose we wished to evaluate the function
`sqrt(x^2 + y^2)` across a regular grid of values.
The `numpy.meshgrid`
function takes two one-dimensional arrays and produces two
two-dimensional matrices corresponding to all pairs of `(x, y)` in the
two arrays:



In [ ]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

Now, evaluating the function is a matter of writing the same expression
you would write with two points:



In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

Here, I used the matplotlib function
`imshow` to create an image plot from a two-dimensional array of
function values.



In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

#### Expressing Conditional Logic as Array



The `numpy.where` function is a vectorized version of the ternary
expression `x if condition else y`. Suppose we had a Boolean array and
two arrays of values:



In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Suppose we wanted to take a value from `xarr` whenever the corresponding
value in `cond` is `True`, and otherwise take the value from `yarr`. A
list comprehension doing this might look like:



In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

This has multiple problems. First, it will not be very fast for large
arrays (because all the work is being done in interpreted Python code).
Second, it will not work with multidimensional arrays. With
`numpy.where` you can do this with a single function call:



In [ ]:
result = np.where(cond, xarr, yarr)
result

The second and third arguments to `numpy.where` don't need to be arrays;
one or both of them can be scalars. A typical use of `where` in data
analysis is to produce a new array of values based on another array.
Suppose you had a matrix of randomly generated data and you wanted to
replace all positive values with 2 and all negative values with &#x2013;2.
This is possible to do with `numpy.where`:



In [ ]:
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

You can combine scalars and arrays when using `numpy.where`. For
example, I can replace all positive values in `arr` with the constant 2,
like so:



In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

#### Mathematical and Statistical



A set of mathematical functions that compute statistics about an entire
array or about the data along an axis are accessible as methods of the
array class. You can use aggregations (sometimes called *reductions*)
like `sum`, `mean`, and `std` (standard deviation) either by calling the
array instance method or using the top-level NumPy function. When you
use the NumPy function, like `numpy.sum`, you have to pass the array you
want to aggregate as the first argument.

Here I generate some normally distributed random data and compute some
aggregate statistics:



In [ ]:
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

Functions like `mean` and `sum` take an optional `axis` argument that
computes the statistic over the given axis, resulting in an array with
one less dimension:



In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

Here, `arr.mean(axis=1)` means "compute mean across the columns," where
`arr.sum(axis=0)` means "compute sum down the rows."

Other methods like `cumsum` and `cumprod` do not aggregate, instead
producing an array of the intermediate results:



In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In multidimensional arrays, accumulation functions like `cumsum` return
an array of the same size but with the partial aggregates computed along
the indicated axis according to each lower dimensional slice:



In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

The expression `arr.cumsum(axis=0)` computes the cumulative sum along
the rows, while `arr.cumsum(axis=1)` computes the sums along the
columns:



In [ ]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)


| Method|Description|
|---|---|
| <code>sum</code>|Sum of all the elements in the array or along an axis; zero-length arrays have sum 0|
| <code>mean</code>|Arithmetic mean; invalid (returns <code>NaN</code>) on zero-length arrays|
| <code>std, var</code>|Standard deviation and variance, respectively|
| <code>min, max</code>|Minimum and maximum|
| <code>argmin, argmax</code>|Indices of minimum and maximum elements, respectively|
| <code>cumsum</code>|Cumulative sum of elements starting from 0|
| <code>cumprod</code>|Cumulative product of elements starting from 1|



#### Methods for Boolean



Boolean values are coerced to 1 (`True`) and 0 (`False`) in the
preceding methods. Thus, `sum` is often used as a means of counting
`True` values in a Boolean array:



In [ ]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

The parentheses here in the expression `(arr > 0).sum()` are necessary
to be able to call `sum()` on the temporary result of `arr > 0`.

Two additional methods, `any` and `all`, are useful especially for
Boolean arrays. `any` tests whether one or more values in an array is
`True`, while `all` checks if every value is `True`:



In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

These methods also work with non-Boolean arrays, where nonzero elements
are treated as `True`.



#### Sorting[[[https://wesmckinney.com/book/numpy-basics#numpy_sorting](https://wesmckinney.com/book/numpy-basics#numpy_sorting)][]]



Like Python's built-in list type, NumPy arrays can be sorted in place
with the `sort` method:



In [ ]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

You can sort each one-dimensional section of values in a
multidimensional array in place along an axis by passing the axis number
to `sort`. In this example data:



In [ ]:
arr = rng.standard_normal((5, 3))
arr

`arr.sort(axis=0)` sorts the values within each column, while
`arr.sort(axis=1)` sorts across each row:



In [ ]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

The top-level method `numpy.sort` returns a sorted copy of an array
(like the Python built-in function `sorted`) instead of modifying the
array in place. For example:



In [ ]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

#### Unique and Other Set



NumPy has some basic set operations for one-dimensional ndarrays. A
commonly used one is `numpy.unique`, which returns the sorted unique
values in an array:



In [ ]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

Contrast `numpy.unique` with the pure Python alternative:



In [ ]:
sorted(set(names))

In many cases, the NumPy version is faster and returns a NumPy array
rather than a Python list.

Another function, `numpy.in1d`, tests membership of the values in one
array in another, returning a Boolean array:



In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

Here is a listing of array set operations in NumPy.


| Method|Description|
|---|---|
| <code>unique(x)</code>|Compute the sorted, unique elements in <code>x</code>|
| <code>intersect1d(x, y)</code>|Compute the sorted, common elements in <code>x</code> and <code>y</code>|
| <code>union1d(x, y)</code>|Compute the sorted union of elements|
| <code>in1d(x, y)</code>|Compute a Boolean array indicating whether each element of <code>x</code> is contained in <code>y</code>|
| <code>setdiff1d(x, y)</code>|Set difference, elements in <code>x</code> that are not in <code>y</code>|
| <code>setxor1d(x, y)</code>|Set symmetric differences; elements that are in either of the arrays, but not both|



### File Input and Output with



NumPy is able to save and load data to and from disk in some text or
binary formats.

`numpy.save` and `numpy.load` are the two workhorse functions for
efficiently saving and loading array data on disk. Arrays are saved by
default in an uncompressed raw binary format with file extension *.npy*:



In [ ]:
arr = np.arange(10)
np.save("some_array", arr)

If the file path does not already end in *.npy*, the extension will be
appended. The array on disk can then be loaded with `numpy.load`:



In [ ]:
np.load("some_array.npy")

You can save multiple arrays in an uncompressed archive using
`numpy.savez` and passing the arrays as keyword arguments:



In [ ]:
np.savez("array_archive.npz", a=arr, b=arr)

When loading an *.npz* file, you get back a dictionary-like object that
loads the individual arrays lazily:



In [ ]:
arch = np.load("array_archive.npz")
arch["b"]

If your data compresses well, you may wish to use
`numpy.savez_compressed` instead:



In [ ]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

### Linear Algebra



Linear algebra operations, like matrix multiplication, decompositions,
determinants, and other square matrix math, are an important part of
many array libraries. Multiplying two two-dimensional arrays with `*` is
an element-wise product, while matrix multiplications require either
using the `dot` function or the `@` infix operator. `dot` is both an
array method and a function in the `numpy` namespace for doing matrix
multiplication:



In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

`x.dot(y)` is equivalent to `np.dot(x, y)`:



In [ ]:
np.dot(x, y)

A matrix product between a two-dimensional array and a suitably sized
one-dimensional array results in a one-dimensional array:



In [ ]:
x @ np.ones(3)

`numpy.linalg` has a standard set of matrix decompositions and things
like inverse and determinant:



In [ ]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
mat @ inv(mat)

The expression `X.T.dot(X)` computes the dot product of `X` with its
transpose `X.T`.

Here is a list of some of the most commonly used linear algebra functions.


| Function|Description|
|---|---|
| <code>diag</code>|Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal|
| <code>dot</code>|Matrix multiplication|
| <code>trace</code>|Compute the sum of the diagonal elements|
| <code>det</code>|Compute the matrix determinant|
| <code>eig</code>|Compute the eigenvalues and eigenvectors of a square matrix|
| <code>inv</code>|Compute the inverse of a square matrix|
| <code>pinv</code>|Compute the Moore-Penrose pseudoinverse of a matrix|
| <code>qr</code>|Compute the QR decomposition|
| <code>svd</code>|Compute the singular value decomposition (SVD)|
| <code>solve</code>|Solve the linear system Ax = b for x, where A is a square matrix|
| <code>lstsq</code>|Compute the least-squares solution to <code>Ax = b</code>|



### Example: Random



The simulation of [*random
walks*](https://en.wikipedia.org/wiki/Random_walk) provides an illustrative application of utilizing array
operations. Let's first consider a simple random walk starting at 0 with
steps of 1 and &#x2013;1 occurring with equal probability.

Here is a pure Python way to implement a single random walk with 1,000
steps using the built-in `random` module:



In [ ]:
#! blockstart
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
#! blockend

In [ ]:
plt.plot(walk[:100])
plt.show()

You might make the observation that `walk` is the cumulative sum of the
random steps and could be evaluated as an array expression. Thus, I use
the `numpy.random` module to draw 1,000 coin flips at once, set these to
1 and &#x2013;1, and compute the cumulative sum:



In [ ]:
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

From this we can begin to extract statistics like the minimum and
maximum value along the walk's trajectory:



In [ ]:
walk.min()
walk.max()

A more complicated statistic is the *first crossing time*, the step at
which the random walk reaches a particular value. Here we might want to
know how long it took the random walk to get at least 10 steps away from
the origin 0 in either direction. `np.abs(walk) >` 10= gives us a
Boolean array indicating where the walk has reached or exceeded 10, but
we want the index of the *first* 10 or &#x2013;10. Turns out, we can compute
this using `argmax`, which returns the first index of the maximum value
in the Boolean array (`True` is the maximum value):



In [ ]:
(np.abs(walk) >= 10).argmax()

Note that using `argmax` here is not always efficient because it always
makes a full scan of the array. In this special case, once a `True` is
observed we know it to be the maximum value.



#### Simulating Many Random Walks at



If your goal was to simulate many random walks, say five thousand of
them, you can generate all of the random walks with minor modifications
to the preceding code. If passed a 2-tuple, the `numpy.random` functions
will generate a two-dimensional array of draws, and we can compute the
cumulative sum for each row to compute all five thousand random walks in
one shot:



In [ ]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

Now, we can compute the maximum and minimum values obtained over all of
the walks:



In [ ]:
walks.max()
walks.min()

Out of these walks, let's compute the minimum crossing time to 30 or
&#x2013;30. This is slightly tricky because not all 5,000 of them reach 30. We
can check this using the `any` method:



In [ ]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

We can use this Boolean array to select the rows of `walks` that
actually cross the absolute 30 level, and call `argmax` across axis 1 to
get the crossing times:



In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times

Lastly, we compute the average minimum crossing time:



In [ ]:
crossing_times.mean()

Feel free to experiment with other distributions for the steps other
than equal-sized coin flips. You need only use a different random
generator method, like `standard_normal` to generate normally
distributed steps with some mean and standard deviation:



In [ ]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))